services:
  dynamodb:
    image: amazon/dynamodb-local:latest
    container_name: meaningful-dynamodb
    command:
      - "-jar"
      - "DynamoDBLocal.jar"
      - "-sharedDb"
      - "-dbPath"
      - "/home/dynamodblocal/data"
    ports:
      - "8000:8000"
    volumes:
      - ./docker/dynamodb:/home/dynamodblocal/data
    networks:
      - meaningful-dev

networks:
  meaningful-dev:
    name: meaningful-dev

